name: Eleventy Build & Deploy

on:
  push:
    branches:
      - master  # se ejecuta cada vez que haya un commit en master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Eleventy site
        run: npx eleventy

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          commit_user_name: "Alberto Prado"
          commit_user_email: "TU_EMAIL@github.com"
