name: Build Eleventy Site Daily

on:
  schedule:
    - cron: '0 3 * * *' # A las 3:00 AM UTC todos los días
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USER_EMAIL: ${{ secrets.USER_EMAIL }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

    steps:

      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Mostrar variables de entorno en bash
        run: |
          echo "USER_EMAIL: $USER_EMAIL"
          echo "USER_PASSWORD: $USER_PASSWORD"

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm ci

      - name: Compilar el sitio con Eleventy
        run: npm run build
        

      - name: Publicar en GitHub Pages (gh-pages)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages